management:
  health:
    probes.enabled: true
    diskspace.enabled: false
    livenessstate.enabled: true
    readinessstate.enabled: true

spring:
  jackson:
    property-naming-strategy: SNAKE_CASE
  kafka:
    bootstrap-servers: http://localhost:29092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
      properties:
        schema.registry.url: http://localhost:9081
        auto.register.schemas: true
        use.latest.version: true
        enable.idempotence: true
        acks: all
        value.subject.name.strategy: io.confluent.kafka.serializers.subject.TopicRecordNameStrategy
    client-id: library-loan
    consumer:
      group-id: reporting
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
      properties:
        schema.registry.url: http://localhost:9081
        specific.avro.reader: true
        value.subject.name.strategy: io.confluent.kafka.serializers.subject.TopicRecordNameStrategy

logging.level:
  org.springframework.web: ERROR
  org.apache.kafka.clients.producer: WARN
  io.confluent.kafka:
    serializers: WARN
    schemaregistry.client: WARN
