version: '3.5'

networks:
  library:
    name: library

services:
  library-loan:
    container_name: library-loan
    image: library-loan:latest
    restart: always
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:8080/actuator/health/liveness || exit 1
      interval: 5s
      timeout: 1s
      retries: 3
    networks:
      - library
