version: '3.5'

networks:
  library:
    name: library

services:
  kafdrop:
    container_name: kafka-ui
    image: obsidiandynamics/kafdrop
    restart: "no"
    ports:
      - "9000:9000"
    environment:
      KAFKA_BROKERCONNECT: broker:9092
      JVM_OPTS: "-Xms16M -Xmx48M -Xss180K -XX:-TieredCompilation -XX:+UseStringDeduplication -noverify"
      SCHEMAREGISTRY_CONNECT: "http://schema-registry:9081"
      CMD_ARGS: "--message.format=AVRO"
    depends_on:
      - broker
    networks:
      - library

  zookeeper:
    container_name: kafka-zookeeper
    image: confluentinc/cp-zookeeper:6.2.7
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    healthcheck:
      test: echo srvr | nc zookeeper 2181 || exit 1
      retries: 20
      interval: 10s
    networks:
      - library

  broker:
    container_name: kafka-broker
    image: confluentinc/cp-kafka:6.2.7
    depends_on:
      - zookeeper
    ports:
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_CONFLUENT_SCHEMA_REGISTRY_URL: http://schema-registry:9081
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'false'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
    networks:
      - library

  schema-registry:
    container_name: schema-registry
    image: ghcr.io/aiven/karapace:3.4.0
    depends_on:
      - broker
    entrypoint:
      - /bin/bash
      - /opt/karapace/start.sh
      - registry
    ports:
      - "9081:9081"
    environment:
      KARAPACE_ADVERTISED_HOSTNAME: schema-registry
      KARAPACE_BOOTSTRAP_URI: broker:9092
      KARAPACE_PORT: 9081
      KARAPACE_HOST: 0.0.0.0
      KARAPACE_CLIENT_ID: schema-registry
      KARAPACE_GROUP_ID: schema-registry
      KARAPACE_MASTER_ELIGIBILITY: "true"
      KARAPACE_TOPIC_NAME: _schemas
      KARAPACE_LOG_LEVEL: INFO
      KARAPACE_COMPATIBILITY: FULL
    networks:
      - library
